node {
    def built_img = ''
    stage('Checkout git repo') {
      git branch: 'test', url: params.git_repo
    }
    
stage('Build Docker Image') {
            when {
                branch 'test'
            }
            steps {
                script {
                    app = docker.build(DOCKER_IMAGE_NAME)
                    app.inside {
                        sh 'echo Hello, World!'
                    }
                }
            }
        }
        stage('Push Docker Image') {
            when {
                branch 'test'
            }
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        app.push("${env.BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }


        stage('DeployToProduction') {
            when {
                branch 'test'
            }
            steps {
                input 'Deploy to Production?'
                milestone(1)
                //implement Kubernetes deployment here
                kubernetesDeploy(
                    kubeconfigId: 'kubeconfig',
                    configs: 'k8s.yml',
                    enableConfigSubstitution: true
                )
            }
        }
    }
